# DataCamp
* DataCampのKaggle titanicデータの分析チュートリアル
* 本サイトは[こちら](https://campus.datacamp.com/courses/kaggle-python-tutorial-on-machine-learning/getting-started-with-python?ex=1)
* サイト内でコードを直接書くことも可能。

In [1]:
import pandas as pd

train = pd.read_csv("./input/train.csv")
test = pd.read_csv("./input/test.csv")

In [2]:
train.shape

(891, 12)

In [3]:
test.shape

(418, 11)

In [4]:
train.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [5]:
# Passengers that survived vs passengers that passed away
print(train["Survived"].value_counts())

# As proportions
print(train["Survived"].value_counts(normalize=True))

# Males that survived vs males that passed away
print(train["Survived"][train["Sex"]=="male"].value_counts())

# Females that survived vs Females that passed away
print(train["Survived"][train["Sex"]=="female"].value_counts())

# Normalized male survival
print(train["Survived"][train["Sex"]=="male"].value_counts(normalize=True))

# Normalized female survival
print(train["Survived"][train["Sex"]=="female"].value_counts(normalize=True))


0    549
1    342
Name: Survived, dtype: int64
0    0.616162
1    0.383838
Name: Survived, dtype: float64
0    468
1    109
Name: Survived, dtype: int64
1    233
0     81
Name: Survived, dtype: int64
0    0.811092
1    0.188908
Name: Survived, dtype: float64
1    0.742038
0    0.257962
Name: Survived, dtype: float64


In [6]:
# Create the column Child and assign to 'NaN'
train["Child"] = float('NaN')

# Assign 1 to passengers under 18, 0 to those 18 or older. Print the new column.
train.loc[train.Age<18,"Child"] = int(1)
train.loc[train.Age>=18,"Child"] = int(0)
print(train["Child"])


# Print normalized Survival Rates for passengers under 18
print(train["Survived"][train["Child"] == 1].value_counts(normalize = True))

# Print normalized Survival Rates for passengers 18 or older
print(train["Survived"][train["Child"] == 0].value_counts(normalize = True))


0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
5      NaN
6      0.0
7      1.0
8      0.0
9      1.0
10     1.0
11     0.0
12     0.0
13     0.0
14     1.0
15     0.0
16     1.0
17     NaN
18     0.0
19     NaN
20     0.0
21     0.0
22     1.0
23     0.0
24     1.0
25     0.0
26     NaN
27     0.0
28     NaN
29     NaN
      ... 
861    0.0
862    0.0
863    NaN
864    0.0
865    0.0
866    0.0
867    0.0
868    NaN
869    1.0
870    0.0
871    0.0
872    0.0
873    0.0
874    0.0
875    1.0
876    0.0
877    0.0
878    NaN
879    0.0
880    0.0
881    0.0
882    0.0
883    0.0
884    0.0
885    0.0
886    0.0
887    0.0
888    NaN
889    0.0
890    0.0
Name: Child, Length: 891, dtype: float64
1    0.539823
0    0.460177
Name: Survived, dtype: float64
0    0.618968
1    0.381032
Name: Survived, dtype: float64


In [7]:
train[["Child","Age"]]

Child   Age
0      0.0  22.0
1      0.0  38.0
2      0.0  26.0
3      0.0  35.0
4      0.0  35.0
5      NaN   NaN
6      0.0  54.0
7      1.0   2.0
8      0.0  27.0
9      1.0  14.0
10     1.0   4.0
11     0.0  58.0
12     0.0  20.0
13     0.0  39.0
14     1.0  14.0
15     0.0  55.0
16     1.0   2.0
17     NaN   NaN
18     0.0  31.0
19     NaN   NaN
20     0.0  35.0
21     0.0  34.0
22     1.0  15.0
23     0.0  28.0
24     1.0   8.0
25     0.0  38.0
26     NaN   NaN
27     0.0  19.0
28     NaN   NaN
29     NaN   NaN
..     ...   ...
861    0.0  21.0
862    0.0  48.0
863    NaN   NaN
864    0.0  24.0
865    0.0  42.0
866    0.0  27.0
867    0.0  31.0
868    NaN   NaN
869    1.0   4.0
870    0.0  26.0
871    0.0  47.0
872    0.0  33.0
873    0.0  47.0
874    0.0  28.0
875    1.0  15.0
876    0.0  20.0
877    0.0  19.0
878    NaN   NaN
879    0.0  56.0
880    0.0  25.0
881    0.0  33.0
882    0.0  22.0
883    0.0  28.0
884    0.0  25.0
885    0.0  39.0
886    0.0  27.0
887    0.0  19.0
888    NaN   NaN
889    0.0  26.0
890    0.0  32.0

[891 rows x 2 columns]

In [8]:
# Create a copy of test: test_one
test_one =test.copy()

# Initialize a Survived column to 0
test_one["Survived"] = 0

# Set Survived to 1 if Sex equals "female" and print the `Survived` column from `test_one`
test_one.loc[test_one.Sex=="female","Survived"] = 1

print(test_one.Survived)

0      0
1      1
2      0
3      0
4      1
5      0
6      1
7      0
8      1
9      0
10     0
11     0
12     1
13     0
14     1
15     1
16     0
17     0
18     1
19     1
20     0
21     0
22     1
23     0
24     1
25     0
26     1
27     0
28     0
29     0
      ..
388    0
389    0
390    0
391    1
392    0
393    0
394    0
395    1
396    0
397    1
398    0
399    0
400    1
401    0
402    1
403    0
404    0
405    0
406    0
407    0
408    1
409    1
410    1
411    1
412    1
413    0
414    1
415    0
416    0
417    0
Name: Survived, Length: 418, dtype: int64


# ここまでの振り返り
* .locの使い方に少しなれた。

In [9]:
# Import the Numpy library
import numpy as np

# Import 'tree' from scikit-learn library
from sklearn import tree

* 続きは[こちら](https://campus.datacamp.com/courses/kaggle-python-tutorial-on-machine-learning/predicting-with-decision-trees?ex=2)

In [10]:
# Convert the male and female groups to integer form
train.loc[train["Sex"] == "male","Sex"] = 0
train.loc[train["Sex"] == "female","Sex"] = 1

# Impute the Embarked variable
train["Embarked"] = train.Embarked.fillna("S")

# Convert the Embarked classes to integer form
train.loc[train["Embarked"] == "S","Embarked"] = 0
train.loc[train["Embarked"] == "C","Embarked"] = 1
train.loc[train["Embarked"] == "Q","Embarked"] = 2

#Print the Sex and Embarked columns
print(train.Sex)
print(train.Embarked)

0      0
1      1
2      1
3      1
4      0
5      0
6      0
7      0
8      1
9      1
10     1
11     1
12     0
13     0
14     1
15     1
16     0
17     0
18     1
19     1
20     0
21     0
22     1
23     0
24     1
25     1
26     0
27     0
28     1
29     0
      ..
861    0
862    1
863    1
864    0
865    1
866    1
867    0
868    0
869    0
870    0
871    1
872    0
873    0
874    1
875    1
876    0
877    0
878    0
879    1
880    1
881    0
882    1
883    0
884    0
885    1
886    0
887    1
888    1
889    0
890    0
Name: Sex, Length: 891, dtype: object
0      0
1      1
2      0
3      0
4      0
5      2
6      0
7      0
8      0
9      1
10     0
11     0
12     0
13     0
14     0
15     0
16     2
17     0
18     0
19     1
20     0
21     0
22     2
23     0
24     0
25     0
26     1
27     0
28     2
29     0
      ..
861    0
862    0
863    0
864    0
865    0
866    1
867    0
868    0
869    0
870    0
871    0
872    0
873    0
874    1
875    1

In [11]:
# Print the train data to see the available features
print(train)

     PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
5              6         0       3   
6              7         0       1   
7              8         0       3   
8              9         1       3   
9             10         1       2   
10            11         1       3   
11            12         1       1   
12            13         0       3   
13            14         0       3   
14            15         0       3   
15            16         1       2   
16            17         0       3   
17            18         1       2   
18            19         0       3   
19            20         1       3   
20            21         0       2   
21            22         1       2   
22            23         1       3   
23            24         1       1   
24            25         0       3   
25          

In [12]:
# Create the target and features numpy arrays: target, features_one
target = train["Survived"].values
features_one = train[["Pclass", "Sex", "Age", "Fare"]].values


In [13]:
features_one

array([[3, 0, 22.0, 7.25],
       [1, 1, 38.0, 71.2833],
       [3, 1, 26.0, 7.925],
       ..., 
       [3, 1, nan, 23.45],
       [1, 0, 26.0, 30.0],
       [3, 0, 32.0, 7.75]], dtype=object)

In [14]:
# 下記はこのjupyter notebook上だと通らなかったが、DataCamp上だと通った。
# Ageにnanがあるようだったが、DataCampではない？
np.sum(pd.isnull(features_one),axis=0)

array([  0,   0, 177,   0])

In [15]:
features_one

array([[3, 0, 22.0, 7.25],
       [1, 1, 38.0, 71.2833],
       [3, 1, 26.0, 7.925],
       ..., 
       [3, 1, nan, 23.45],
       [1, 0, 26.0, 30.0],
       [3, 0, 32.0, 7.75]], dtype=object)

In [16]:
train.Age.median()

28.0

In [17]:
train.loc[pd.isnull(train.Age),"Age"] = train.Age.median()
features_one = train[["Pclass", "Sex", "Age", "Fare"]].values

In [18]:

# Fit your first decision tree: my_tree_one
my_tree_one = tree.DecisionTreeClassifier()
my_tree_one = my_tree_one.fit(features_one, target)

# Look at the importance and score of the included features
print(my_tree_one.feature_importances_)
print(my_tree_one.score(features_one, target))

[ 0.12315342  0.31274009  0.22530797  0.33879851]
0.977553310887


In [19]:
pd.isnull(train.Sex) 

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
       ...  
861    False
862    False
863    False
864    False
865    False
866    False
867    False
868    False
869    False
870    False
871    False
872    False
873    False
874    False
875    False
876    False
877    False
878    False
879    False
880    False
881    False
882    False
883    False
884    False
885    False
886    False
887    False
888    False
889    False
890    False
Name: Sex, Length: 891, dtype: bool

In [20]:
np.sum(pd.isnull(features_one))

0

* pd.isnull()について学んだ、